// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPCPacket.proto

#include "RPCPacket.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace DSFramework {
namespace DSRPC {
namespace Packet {

inline constexpr RPCPacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        from_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        to_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        from_inner_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        created_time_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        commited_time_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        completed_time_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        request_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        service_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        parameters_{nullptr},
        result_{nullptr},
        type_{static_cast< ::DSFramework::DSRPC::Packet::RPCPacketType >(0)},
        error_{static_cast< ::DSFramework::DSRPC::Packet::RPCPacketError >(0)},
        status_{static_cast< ::DSFramework::DSRPC::Packet::RPCPacketStatus >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR RPCPacket::RPCPacket(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RPCPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RPCPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPCPacketDefaultTypeInternal() {}
  union {
    RPCPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPCPacketDefaultTypeInternal _RPCPacket_default_instance_;
}  // namespace Packet
}  // namespace DSRPC
}  // namespace DSFramework
static ::_pb::Metadata file_level_metadata_RPCPacket_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_RPCPacket_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_RPCPacket_2eproto = nullptr;
const ::uint32_t TableStruct_RPCPacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.type_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.error_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.status_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.from_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.to_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.from_inner_id_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.created_time_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.commited_time_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.completed_time_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.request_id_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.service_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.parameters_),
    PROTOBUF_FIELD_OFFSET(::DSFramework::DSRPC::Packet::RPCPacket, _impl_.result_),
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    0,
    1,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 21, -1, sizeof(::DSFramework::DSRPC::Packet::RPCPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::DSFramework::DSRPC::Packet::_RPCPacket_default_instance_._instance,
};
const char descriptor_table_protodef_RPCPacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017RPCPacket.proto\022\030DSFramework.DSRPC.Pac"
    "ket\032\031google/protobuf/any.proto\"\241\003\n\tRPCPa"
    "cket\0225\n\004type\030\001 \001(\0162\'.DSFramework.DSRPC.P"
    "acket.RPCPacketType\0227\n\005error\030\002 \001(\0162(.DSF"
    "ramework.DSRPC.Packet.RPCPacketError\0229\n\006"
    "status\030\003 \001(\0162).DSFramework.DSRPC.Packet."
    "RPCPacketStatus\022\014\n\004from\030\004 \001(\t\022\n\n\002to\030\005 \001("
    "\t\022\025\n\rfrom_inner_id\030\006 \001(\t\022\024\n\014created_time"
    "\030\007 \001(\t\022\025\n\rcommited_time\030\010 \001(\t\022\026\n\016complet"
    "ed_time\030\t \001(\t\022\022\n\nrequest_id\030\n \001(\t\022\017\n\007ser"
    "vice\030\013 \001(\t\022(\n\nparameters\030\014 \001(\0132\024.google."
    "protobuf.Any\022$\n\006result\030\r \001(\0132\024.google.pr"
    "otobuf.Any*\272\001\n\016RPCPacketError\022\013\n\007UNKNOWN"
    "\020\000\022\014\n\010NO_ERROR\020\001\022\027\n\023SERIALIZATION_ERROR\020"
    "\002\022\031\n\025DESERIALIZATION_ERROR\020\003\022\020\n\014SERVICE_"
    "BUSY\020\004\022\025\n\021SERVICE_NOT_FOUND\020\005\022\035\n\031SERVICE"
    "_IVAILD_PARAMETERS\020\006\022\021\n\rSERVICE_ERROR\020\007*"
    "[\n\rRPCPacketType\022\020\n\014TASK_REQUEST\020\000\022\021\n\rTA"
    "SK_RESPONSE\020\001\022\021\n\rQUERY_REQUEST\020\002\022\022\n\016QUER"
    "Y_RESPONSE\020\003*;\n\017RPCPacketStatus\022\013\n\007WAITI"
    "NG\020\000\022\014\n\010COMMITED\020\001\022\r\n\tCOMPLETED\020\002b\006proto"
    "3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_RPCPacket_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fany_2eproto,
};
static ::absl::once_flag descriptor_table_RPCPacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_RPCPacket_2eproto = {
    false,
    false,
    841,
    descriptor_table_protodef_RPCPacket_2eproto,
    "RPCPacket.proto",
    &descriptor_table_RPCPacket_2eproto_once,
    descriptor_table_RPCPacket_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_RPCPacket_2eproto::offsets,
    file_level_metadata_RPCPacket_2eproto,
    file_level_enum_descriptors_RPCPacket_2eproto,
    file_level_service_descriptors_RPCPacket_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_RPCPacket_2eproto_getter() {
  return &descriptor_table_RPCPacket_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_RPCPacket_2eproto(&descriptor_table_RPCPacket_2eproto);
namespace DSFramework {
namespace DSRPC {
namespace Packet {
const ::google::protobuf::EnumDescriptor* RPCPacketError_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_RPCPacket_2eproto);
  return file_level_enum_descriptors_RPCPacket_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RPCPacketError_internal_data_[] = {
    524288u, 0u, };
bool RPCPacketError_IsValid(int value) {
  return 0 <= value && value <= 7;
}
const ::google::protobuf::EnumDescriptor* RPCPacketType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_RPCPacket_2eproto);
  return file_level_enum_descriptors_RPCPacket_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t RPCPacketType_internal_data_[] = {
    262144u, 0u, };
bool RPCPacketType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* RPCPacketStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_RPCPacket_2eproto);
  return file_level_enum_descriptors_RPCPacket_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t RPCPacketStatus_internal_data_[] = {
    196608u, 0u, };
bool RPCPacketStatus_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class RPCPacket::_Internal {
 public:
  using HasBits = decltype(std::declval<RPCPacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_._has_bits_);
  static const ::google::protobuf::Any& parameters(const RPCPacket* msg);
  static void set_has_parameters(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::google::protobuf::Any& result(const RPCPacket* msg);
  static void set_has_result(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::google::protobuf::Any& RPCPacket::_Internal::parameters(const RPCPacket* msg) {
  return *msg->_impl_.parameters_;
}
const ::google::protobuf::Any& RPCPacket::_Internal::result(const RPCPacket* msg) {
  return *msg->_impl_.result_;
}
void RPCPacket::clear_parameters() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.parameters_ != nullptr) _impl_.parameters_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void RPCPacket::clear_result() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.result_ != nullptr) _impl_.result_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
RPCPacket::RPCPacket(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DSFramework.DSRPC.Packet.RPCPacket)
}
inline PROTOBUF_NDEBUG_INLINE RPCPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        from_(arena, from.from_),
        to_(arena, from.to_),
        from_inner_id_(arena, from.from_inner_id_),
        created_time_(arena, from.created_time_),
        commited_time_(arena, from.commited_time_),
        completed_time_(arena, from.completed_time_),
        request_id_(arena, from.request_id_),
        service_(arena, from.service_) {}

RPCPacket::RPCPacket(
    ::google::protobuf::Arena* arena,
    const RPCPacket& from)
    : ::google::protobuf::Message(arena) {
  RPCPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.parameters_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::protobuf::Any>(arena, *from._impl_.parameters_)
                : nullptr;
  _impl_.result_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::google::protobuf::Any>(arena, *from._impl_.result_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, status_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::status_));

  // @@protoc_insertion_point(copy_constructor:DSFramework.DSRPC.Packet.RPCPacket)
}
inline PROTOBUF_NDEBUG_INLINE RPCPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        from_(arena),
        to_(arena),
        from_inner_id_(arena),
        created_time_(arena),
        commited_time_(arena),
        completed_time_(arena),
        request_id_(arena),
        service_(arena) {}

inline void RPCPacket::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, parameters_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, parameters_) +
               sizeof(Impl_::status_));
}
RPCPacket::~RPCPacket() {
  // @@protoc_insertion_point(destructor:DSFramework.DSRPC.Packet.RPCPacket)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RPCPacket::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.from_.Destroy();
  _impl_.to_.Destroy();
  _impl_.from_inner_id_.Destroy();
  _impl_.created_time_.Destroy();
  _impl_.commited_time_.Destroy();
  _impl_.completed_time_.Destroy();
  _impl_.request_id_.Destroy();
  _impl_.service_.Destroy();
  delete _impl_.parameters_;
  delete _impl_.result_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RPCPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:DSFramework.DSRPC.Packet.RPCPacket)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.from_.ClearToEmpty();
  _impl_.to_.ClearToEmpty();
  _impl_.from_inner_id_.ClearToEmpty();
  _impl_.created_time_.ClearToEmpty();
  _impl_.commited_time_.ClearToEmpty();
  _impl_.completed_time_.ClearToEmpty();
  _impl_.request_id_.ClearToEmpty();
  _impl_.service_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.parameters_ != nullptr);
      _impl_.parameters_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.result_ != nullptr);
      _impl_.result_->Clear();
    }
  }
  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.status_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.status_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RPCPacket::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 13, 2, 126, 2> RPCPacket::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_._has_bits_),
    0, // no _extensions_
    13, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294959104,  // skipmap
    offsetof(decltype(_table_), field_entries),
    13,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_RPCPacket_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .DSFramework.DSRPC.Packet.RPCPacketType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPCPacket, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.type_)}},
    // .DSFramework.DSRPC.Packet.RPCPacketError error = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPCPacket, _impl_.error_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.error_)}},
    // .DSFramework.DSRPC.Packet.RPCPacketStatus status = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPCPacket, _impl_.status_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.status_)}},
    // string from = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.from_)}},
    // string to = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.to_)}},
    // string from_inner_id = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.from_inner_id_)}},
    // string created_time = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.created_time_)}},
    // string commited_time = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.commited_time_)}},
    // string completed_time = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.completed_time_)}},
    // string request_id = 10;
    {::_pbi::TcParser::FastUS1,
     {82, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.request_id_)}},
    // string service = 11;
    {::_pbi::TcParser::FastUS1,
     {90, 63, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.service_)}},
    // .google.protobuf.Any parameters = 12;
    {::_pbi::TcParser::FastMtS1,
     {98, 0, 0, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.parameters_)}},
    // .google.protobuf.Any result = 13;
    {::_pbi::TcParser::FastMtS1,
     {106, 1, 1, PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.result_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .DSFramework.DSRPC.Packet.RPCPacketType type = 1;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .DSFramework.DSRPC.Packet.RPCPacketError error = 2;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.error_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .DSFramework.DSRPC.Packet.RPCPacketStatus status = 3;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.status_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string from = 4;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.from_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string to = 5;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.to_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string from_inner_id = 6;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.from_inner_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string created_time = 7;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.created_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string commited_time = 8;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.commited_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string completed_time = 9;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.completed_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string request_id = 10;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.request_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string service = 11;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.service_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Any parameters = 12;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.parameters_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Any result = 13;
    {PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.result_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
  }}, {{
    "\42\0\0\0\4\2\15\14\15\16\12\7\0\0\0\0"
    "DSFramework.DSRPC.Packet.RPCPacket"
    "from"
    "to"
    "from_inner_id"
    "created_time"
    "commited_time"
    "completed_time"
    "request_id"
    "service"
  }},
};

::uint8_t* RPCPacket::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DSFramework.DSRPC.Packet.RPCPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .DSFramework.DSRPC.Packet.RPCPacketType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_type(), target);
  }

  // .DSFramework.DSRPC.Packet.RPCPacketError error = 2;
  if (this->_internal_error() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_error(), target);
  }

  // .DSFramework.DSRPC.Packet.RPCPacketStatus status = 3;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this->_internal_status(), target);
  }

  // string from = 4;
  if (!this->_internal_from().empty()) {
    const std::string& _s = this->_internal_from();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DSFramework.DSRPC.Packet.RPCPacket.from");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string to = 5;
  if (!this->_internal_to().empty()) {
    const std::string& _s = this->_internal_to();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DSFramework.DSRPC.Packet.RPCPacket.to");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // string from_inner_id = 6;
  if (!this->_internal_from_inner_id().empty()) {
    const std::string& _s = this->_internal_from_inner_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DSFramework.DSRPC.Packet.RPCPacket.from_inner_id");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // string created_time = 7;
  if (!this->_internal_created_time().empty()) {
    const std::string& _s = this->_internal_created_time();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DSFramework.DSRPC.Packet.RPCPacket.created_time");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  // string commited_time = 8;
  if (!this->_internal_commited_time().empty()) {
    const std::string& _s = this->_internal_commited_time();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DSFramework.DSRPC.Packet.RPCPacket.commited_time");
    target = stream->WriteStringMaybeAliased(8, _s, target);
  }

  // string completed_time = 9;
  if (!this->_internal_completed_time().empty()) {
    const std::string& _s = this->_internal_completed_time();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DSFramework.DSRPC.Packet.RPCPacket.completed_time");
    target = stream->WriteStringMaybeAliased(9, _s, target);
  }

  // string request_id = 10;
  if (!this->_internal_request_id().empty()) {
    const std::string& _s = this->_internal_request_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DSFramework.DSRPC.Packet.RPCPacket.request_id");
    target = stream->WriteStringMaybeAliased(10, _s, target);
  }

  // string service = 11;
  if (!this->_internal_service().empty()) {
    const std::string& _s = this->_internal_service();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DSFramework.DSRPC.Packet.RPCPacket.service");
    target = stream->WriteStringMaybeAliased(11, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Any parameters = 12;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        12, _Internal::parameters(this),
        _Internal::parameters(this).GetCachedSize(), target, stream);
  }

  // .google.protobuf.Any result = 13;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        13, _Internal::result(this),
        _Internal::result(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DSFramework.DSRPC.Packet.RPCPacket)
  return target;
}

::size_t RPCPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DSFramework.DSRPC.Packet.RPCPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string from = 4;
  if (!this->_internal_from().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_from());
  }

  // string to = 5;
  if (!this->_internal_to().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_to());
  }

  // string from_inner_id = 6;
  if (!this->_internal_from_inner_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_from_inner_id());
  }

  // string created_time = 7;
  if (!this->_internal_created_time().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_created_time());
  }

  // string commited_time = 8;
  if (!this->_internal_commited_time().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_commited_time());
  }

  // string completed_time = 9;
  if (!this->_internal_completed_time().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_completed_time());
  }

  // string request_id = 10;
  if (!this->_internal_request_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_request_id());
  }

  // string service = 11;
  if (!this->_internal_service().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_service());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .google.protobuf.Any parameters = 12;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.parameters_);
    }

    // .google.protobuf.Any result = 13;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.result_);
    }

  }
  // .DSFramework.DSRPC.Packet.RPCPacketType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // .DSFramework.DSRPC.Packet.RPCPacketError error = 2;
  if (this->_internal_error() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_error());
  }

  // .DSFramework.DSRPC.Packet.RPCPacketStatus status = 3;
  if (this->_internal_status() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RPCPacket::_class_data_ = {
    RPCPacket::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RPCPacket::GetClassData() const {
  return &_class_data_;
}

void RPCPacket::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RPCPacket*>(&to_msg);
  auto& from = static_cast<const RPCPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DSFramework.DSRPC.Packet.RPCPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_from().empty()) {
    _this->_internal_set_from(from._internal_from());
  }
  if (!from._internal_to().empty()) {
    _this->_internal_set_to(from._internal_to());
  }
  if (!from._internal_from_inner_id().empty()) {
    _this->_internal_set_from_inner_id(from._internal_from_inner_id());
  }
  if (!from._internal_created_time().empty()) {
    _this->_internal_set_created_time(from._internal_created_time());
  }
  if (!from._internal_commited_time().empty()) {
    _this->_internal_set_commited_time(from._internal_commited_time());
  }
  if (!from._internal_completed_time().empty()) {
    _this->_internal_set_completed_time(from._internal_completed_time());
  }
  if (!from._internal_request_id().empty()) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  if (!from._internal_service().empty()) {
    _this->_internal_set_service(from._internal_service());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_parameters()->::google::protobuf::Any::MergeFrom(
          from._internal_parameters());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_result()->::google::protobuf::Any::MergeFrom(
          from._internal_result());
    }
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_error() != 0) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RPCPacket::CopyFrom(const RPCPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DSFramework.DSRPC.Packet.RPCPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RPCPacket::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RPCPacket::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RPCPacket::InternalSwap(RPCPacket* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.from_, &other->_impl_.from_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.to_, &other->_impl_.to_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.from_inner_id_, &other->_impl_.from_inner_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.created_time_, &other->_impl_.created_time_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.commited_time_, &other->_impl_.commited_time_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.completed_time_, &other->_impl_.completed_time_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.request_id_, &other->_impl_.request_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.service_, &other->_impl_.service_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.status_)
      + sizeof(RPCPacket::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(RPCPacket, _impl_.parameters_)>(
          reinterpret_cast<char*>(&_impl_.parameters_),
          reinterpret_cast<char*>(&other->_impl_.parameters_));
}

::google::protobuf::Metadata RPCPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RPCPacket_2eproto_getter, &descriptor_table_RPCPacket_2eproto_once,
      file_level_metadata_RPCPacket_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Packet
}  // namespace DSRPC
}  // namespace DSFramework
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
