// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPCPacket.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_RPCPacket_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_RPCPacket_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/any.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_RPCPacket_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_RPCPacket_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_RPCPacket_2eproto;
namespace DSFramework {
namespace DSRPC {
namespace Packet {
class RPCPacket;
struct RPCPacketDefaultTypeInternal;
extern RPCPacketDefaultTypeInternal _RPCPacket_default_instance_;
}  // namespace Packet
}  // namespace DSRPC
}  // namespace DSFramework
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace DSFramework {
namespace DSRPC {
namespace Packet {
enum RPCPacketError : int {
  PKT_UNKNOWN = 0,
  PKT_NO_ERROR = 1,
  PKT_SERIALIZATION_ERROR = 2,
  PKT_DESERIALIZATION_ERROR = 3,
  SERVICE_BUSY = 4,
  SERVICE_NOT_FOUND = 5,
  SERVICE_IVAILD_PARAMETERS = 6,
  SERVICE_ERROR = 7,
  RPCPacketError_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  RPCPacketError_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool RPCPacketError_IsValid(int value);
extern const uint32_t RPCPacketError_internal_data_[];
constexpr RPCPacketError RPCPacketError_MIN = static_cast<RPCPacketError>(0);
constexpr RPCPacketError RPCPacketError_MAX = static_cast<RPCPacketError>(7);
constexpr int RPCPacketError_ARRAYSIZE = 7 + 1;
const ::google::protobuf::EnumDescriptor*
RPCPacketError_descriptor();
template <typename T>
const std::string& RPCPacketError_Name(T value) {
  static_assert(std::is_same<T, RPCPacketError>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RPCPacketError_Name().");
  return RPCPacketError_Name(static_cast<RPCPacketError>(value));
}
template <>
inline const std::string& RPCPacketError_Name(RPCPacketError value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RPCPacketError_descriptor,
                                                 0, 7>(
      static_cast<int>(value));
}
inline bool RPCPacketError_Parse(absl::string_view name, RPCPacketError* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RPCPacketError>(
      RPCPacketError_descriptor(), name, value);
}
enum RPCPacketType : int {
  DEFAULT_RESPONSE = 0,
  TASK_REQUEST = 1,
  TASK_RESPONSE = 2,
  QUERY_REQUEST = 3,
  QUERY_RESPONSE = 4,
  RPCPacketType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  RPCPacketType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool RPCPacketType_IsValid(int value);
extern const uint32_t RPCPacketType_internal_data_[];
constexpr RPCPacketType RPCPacketType_MIN = static_cast<RPCPacketType>(0);
constexpr RPCPacketType RPCPacketType_MAX = static_cast<RPCPacketType>(4);
constexpr int RPCPacketType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
RPCPacketType_descriptor();
template <typename T>
const std::string& RPCPacketType_Name(T value) {
  static_assert(std::is_same<T, RPCPacketType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RPCPacketType_Name().");
  return RPCPacketType_Name(static_cast<RPCPacketType>(value));
}
template <>
inline const std::string& RPCPacketType_Name(RPCPacketType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RPCPacketType_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool RPCPacketType_Parse(absl::string_view name, RPCPacketType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RPCPacketType>(
      RPCPacketType_descriptor(), name, value);
}
enum RPCPacketStatus : int {
  WAITING = 0,
  COMMITED = 1,
  COMPLETED = 2,
  RPCPacketStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  RPCPacketStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool RPCPacketStatus_IsValid(int value);
extern const uint32_t RPCPacketStatus_internal_data_[];
constexpr RPCPacketStatus RPCPacketStatus_MIN = static_cast<RPCPacketStatus>(0);
constexpr RPCPacketStatus RPCPacketStatus_MAX = static_cast<RPCPacketStatus>(2);
constexpr int RPCPacketStatus_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
RPCPacketStatus_descriptor();
template <typename T>
const std::string& RPCPacketStatus_Name(T value) {
  static_assert(std::is_same<T, RPCPacketStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RPCPacketStatus_Name().");
  return RPCPacketStatus_Name(static_cast<RPCPacketStatus>(value));
}
template <>
inline const std::string& RPCPacketStatus_Name(RPCPacketStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RPCPacketStatus_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool RPCPacketStatus_Parse(absl::string_view name, RPCPacketStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RPCPacketStatus>(
      RPCPacketStatus_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class RPCPacket final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DSFramework.DSRPC.Packet.RPCPacket) */ {
 public:
  inline RPCPacket() : RPCPacket(nullptr) {}
  ~RPCPacket() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR RPCPacket(::google::protobuf::internal::ConstantInitialized);

  inline RPCPacket(const RPCPacket& from)
      : RPCPacket(nullptr, from) {}
  RPCPacket(RPCPacket&& from) noexcept
    : RPCPacket() {
    *this = ::std::move(from);
  }

  inline RPCPacket& operator=(const RPCPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPCPacket& operator=(RPCPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPCPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const RPCPacket* internal_default_instance() {
    return reinterpret_cast<const RPCPacket*>(
               &_RPCPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RPCPacket& a, RPCPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(RPCPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPCPacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPCPacket* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RPCPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPCPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const RPCPacket& from) {
    RPCPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(RPCPacket* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "DSFramework.DSRPC.Packet.RPCPacket";
  }
  protected:
  explicit RPCPacket(::google::protobuf::Arena* arena);
  RPCPacket(::google::protobuf::Arena* arena, const RPCPacket& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFromFieldNumber = 4,
    kToFieldNumber = 5,
    kInnerIdFieldNumber = 6,
    kCreatedTimeFieldNumber = 7,
    kCommitedTimeFieldNumber = 8,
    kCompletedTimeFieldNumber = 9,
    kRequestIdFieldNumber = 10,
    kServiceFieldNumber = 11,
    kParametersFieldNumber = 12,
    kResultFieldNumber = 13,
    kTypeFieldNumber = 1,
    kErrorFieldNumber = 2,
    kStatusFieldNumber = 3,
  };
  // string from = 4;
  void clear_from() ;
  const std::string& from() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_from(Arg_&& arg, Args_... args);
  std::string* mutable_from();
  PROTOBUF_NODISCARD std::string* release_from();
  void set_allocated_from(std::string* value);

  private:
  const std::string& _internal_from() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_from(
      const std::string& value);
  std::string* _internal_mutable_from();

  public:
  // string to = 5;
  void clear_to() ;
  const std::string& to() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_to(Arg_&& arg, Args_... args);
  std::string* mutable_to();
  PROTOBUF_NODISCARD std::string* release_to();
  void set_allocated_to(std::string* value);

  private:
  const std::string& _internal_to() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_to(
      const std::string& value);
  std::string* _internal_mutable_to();

  public:
  // string inner_id = 6;
  void clear_inner_id() ;
  const std::string& inner_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_inner_id(Arg_&& arg, Args_... args);
  std::string* mutable_inner_id();
  PROTOBUF_NODISCARD std::string* release_inner_id();
  void set_allocated_inner_id(std::string* value);

  private:
  const std::string& _internal_inner_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inner_id(
      const std::string& value);
  std::string* _internal_mutable_inner_id();

  public:
  // string created_time = 7;
  void clear_created_time() ;
  const std::string& created_time() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_created_time(Arg_&& arg, Args_... args);
  std::string* mutable_created_time();
  PROTOBUF_NODISCARD std::string* release_created_time();
  void set_allocated_created_time(std::string* value);

  private:
  const std::string& _internal_created_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_created_time(
      const std::string& value);
  std::string* _internal_mutable_created_time();

  public:
  // string commited_time = 8;
  void clear_commited_time() ;
  const std::string& commited_time() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_commited_time(Arg_&& arg, Args_... args);
  std::string* mutable_commited_time();
  PROTOBUF_NODISCARD std::string* release_commited_time();
  void set_allocated_commited_time(std::string* value);

  private:
  const std::string& _internal_commited_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_commited_time(
      const std::string& value);
  std::string* _internal_mutable_commited_time();

  public:
  // string completed_time = 9;
  void clear_completed_time() ;
  const std::string& completed_time() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_completed_time(Arg_&& arg, Args_... args);
  std::string* mutable_completed_time();
  PROTOBUF_NODISCARD std::string* release_completed_time();
  void set_allocated_completed_time(std::string* value);

  private:
  const std::string& _internal_completed_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_completed_time(
      const std::string& value);
  std::string* _internal_mutable_completed_time();

  public:
  // string request_id = 10;
  void clear_request_id() ;
  const std::string& request_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_request_id(Arg_&& arg, Args_... args);
  std::string* mutable_request_id();
  PROTOBUF_NODISCARD std::string* release_request_id();
  void set_allocated_request_id(std::string* value);

  private:
  const std::string& _internal_request_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_request_id(
      const std::string& value);
  std::string* _internal_mutable_request_id();

  public:
  // string service = 11;
  void clear_service() ;
  const std::string& service() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_service(Arg_&& arg, Args_... args);
  std::string* mutable_service();
  PROTOBUF_NODISCARD std::string* release_service();
  void set_allocated_service(std::string* value);

  private:
  const std::string& _internal_service() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_service(
      const std::string& value);
  std::string* _internal_mutable_service();

  public:
  // .google.protobuf.Any parameters = 12;
  bool has_parameters() const;
  void clear_parameters() ;
  const ::google::protobuf::Any& parameters() const;
  PROTOBUF_NODISCARD ::google::protobuf::Any* release_parameters();
  ::google::protobuf::Any* mutable_parameters();
  void set_allocated_parameters(::google::protobuf::Any* value);
  void unsafe_arena_set_allocated_parameters(::google::protobuf::Any* value);
  ::google::protobuf::Any* unsafe_arena_release_parameters();

  private:
  const ::google::protobuf::Any& _internal_parameters() const;
  ::google::protobuf::Any* _internal_mutable_parameters();

  public:
  // .google.protobuf.Any result = 13;
  bool has_result() const;
  void clear_result() ;
  const ::google::protobuf::Any& result() const;
  PROTOBUF_NODISCARD ::google::protobuf::Any* release_result();
  ::google::protobuf::Any* mutable_result();
  void set_allocated_result(::google::protobuf::Any* value);
  void unsafe_arena_set_allocated_result(::google::protobuf::Any* value);
  ::google::protobuf::Any* unsafe_arena_release_result();

  private:
  const ::google::protobuf::Any& _internal_result() const;
  ::google::protobuf::Any* _internal_mutable_result();

  public:
  // .DSFramework.DSRPC.Packet.RPCPacketType type = 1;
  void clear_type() ;
  ::DSFramework::DSRPC::Packet::RPCPacketType type() const;
  void set_type(::DSFramework::DSRPC::Packet::RPCPacketType value);

  private:
  ::DSFramework::DSRPC::Packet::RPCPacketType _internal_type() const;
  void _internal_set_type(::DSFramework::DSRPC::Packet::RPCPacketType value);

  public:
  // .DSFramework.DSRPC.Packet.RPCPacketError error = 2;
  void clear_error() ;
  ::DSFramework::DSRPC::Packet::RPCPacketError error() const;
  void set_error(::DSFramework::DSRPC::Packet::RPCPacketError value);

  private:
  ::DSFramework::DSRPC::Packet::RPCPacketError _internal_error() const;
  void _internal_set_error(::DSFramework::DSRPC::Packet::RPCPacketError value);

  public:
  // .DSFramework.DSRPC.Packet.RPCPacketStatus status = 3;
  void clear_status() ;
  ::DSFramework::DSRPC::Packet::RPCPacketStatus status() const;
  void set_status(::DSFramework::DSRPC::Packet::RPCPacketStatus value);

  private:
  ::DSFramework::DSRPC::Packet::RPCPacketStatus _internal_status() const;
  void _internal_set_status(::DSFramework::DSRPC::Packet::RPCPacketStatus value);

  public:
  // @@protoc_insertion_point(class_scope:DSFramework.DSRPC.Packet.RPCPacket)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 13, 2,
      121, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr from_;
    ::google::protobuf::internal::ArenaStringPtr to_;
    ::google::protobuf::internal::ArenaStringPtr inner_id_;
    ::google::protobuf::internal::ArenaStringPtr created_time_;
    ::google::protobuf::internal::ArenaStringPtr commited_time_;
    ::google::protobuf::internal::ArenaStringPtr completed_time_;
    ::google::protobuf::internal::ArenaStringPtr request_id_;
    ::google::protobuf::internal::ArenaStringPtr service_;
    ::google::protobuf::Any* parameters_;
    ::google::protobuf::Any* result_;
    int type_;
    int error_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RPCPacket_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RPCPacket

// .DSFramework.DSRPC.Packet.RPCPacketType type = 1;
inline void RPCPacket::clear_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.type_ = 0;
}
inline ::DSFramework::DSRPC::Packet::RPCPacketType RPCPacket::type() const {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.type)
  return _internal_type();
}
inline void RPCPacket::set_type(::DSFramework::DSRPC::Packet::RPCPacketType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.type)
}
inline ::DSFramework::DSRPC::Packet::RPCPacketType RPCPacket::_internal_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::DSFramework::DSRPC::Packet::RPCPacketType>(_impl_.type_);
}
inline void RPCPacket::_internal_set_type(::DSFramework::DSRPC::Packet::RPCPacketType value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.type_ = value;
}

// .DSFramework.DSRPC.Packet.RPCPacketError error = 2;
inline void RPCPacket::clear_error() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.error_ = 0;
}
inline ::DSFramework::DSRPC::Packet::RPCPacketError RPCPacket::error() const {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.error)
  return _internal_error();
}
inline void RPCPacket::set_error(::DSFramework::DSRPC::Packet::RPCPacketError value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.error)
}
inline ::DSFramework::DSRPC::Packet::RPCPacketError RPCPacket::_internal_error() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::DSFramework::DSRPC::Packet::RPCPacketError>(_impl_.error_);
}
inline void RPCPacket::_internal_set_error(::DSFramework::DSRPC::Packet::RPCPacketError value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.error_ = value;
}

// .DSFramework.DSRPC.Packet.RPCPacketStatus status = 3;
inline void RPCPacket::clear_status() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.status_ = 0;
}
inline ::DSFramework::DSRPC::Packet::RPCPacketStatus RPCPacket::status() const {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.status)
  return _internal_status();
}
inline void RPCPacket::set_status(::DSFramework::DSRPC::Packet::RPCPacketStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.status)
}
inline ::DSFramework::DSRPC::Packet::RPCPacketStatus RPCPacket::_internal_status() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::DSFramework::DSRPC::Packet::RPCPacketStatus>(_impl_.status_);
}
inline void RPCPacket::_internal_set_status(::DSFramework::DSRPC::Packet::RPCPacketStatus value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.status_ = value;
}

// string from = 4;
inline void RPCPacket::clear_from() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.from_.ClearToEmpty();
}
inline const std::string& RPCPacket::from() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.from)
  return _internal_from();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPCPacket::set_from(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.from_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.from)
}
inline std::string* RPCPacket::mutable_from() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_from();
  // @@protoc_insertion_point(field_mutable:DSFramework.DSRPC.Packet.RPCPacket.from)
  return _s;
}
inline const std::string& RPCPacket::_internal_from() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.from_.Get();
}
inline void RPCPacket::_internal_set_from(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.from_.Set(value, GetArena());
}
inline std::string* RPCPacket::_internal_mutable_from() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.from_.Mutable( GetArena());
}
inline std::string* RPCPacket::release_from() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DSFramework.DSRPC.Packet.RPCPacket.from)
  return _impl_.from_.Release();
}
inline void RPCPacket::set_allocated_from(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.from_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.from_.IsDefault()) {
          _impl_.from_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.from)
}

// string to = 5;
inline void RPCPacket::clear_to() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.to_.ClearToEmpty();
}
inline const std::string& RPCPacket::to() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.to)
  return _internal_to();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPCPacket::set_to(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.to_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.to)
}
inline std::string* RPCPacket::mutable_to() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_to();
  // @@protoc_insertion_point(field_mutable:DSFramework.DSRPC.Packet.RPCPacket.to)
  return _s;
}
inline const std::string& RPCPacket::_internal_to() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.to_.Get();
}
inline void RPCPacket::_internal_set_to(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.to_.Set(value, GetArena());
}
inline std::string* RPCPacket::_internal_mutable_to() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.to_.Mutable( GetArena());
}
inline std::string* RPCPacket::release_to() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DSFramework.DSRPC.Packet.RPCPacket.to)
  return _impl_.to_.Release();
}
inline void RPCPacket::set_allocated_to(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.to_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.to_.IsDefault()) {
          _impl_.to_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.to)
}

// string inner_id = 6;
inline void RPCPacket::clear_inner_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.inner_id_.ClearToEmpty();
}
inline const std::string& RPCPacket::inner_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.inner_id)
  return _internal_inner_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPCPacket::set_inner_id(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.inner_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.inner_id)
}
inline std::string* RPCPacket::mutable_inner_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_inner_id();
  // @@protoc_insertion_point(field_mutable:DSFramework.DSRPC.Packet.RPCPacket.inner_id)
  return _s;
}
inline const std::string& RPCPacket::_internal_inner_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.inner_id_.Get();
}
inline void RPCPacket::_internal_set_inner_id(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.inner_id_.Set(value, GetArena());
}
inline std::string* RPCPacket::_internal_mutable_inner_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.inner_id_.Mutable( GetArena());
}
inline std::string* RPCPacket::release_inner_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DSFramework.DSRPC.Packet.RPCPacket.inner_id)
  return _impl_.inner_id_.Release();
}
inline void RPCPacket::set_allocated_inner_id(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.inner_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.inner_id_.IsDefault()) {
          _impl_.inner_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.inner_id)
}

// string created_time = 7;
inline void RPCPacket::clear_created_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.created_time_.ClearToEmpty();
}
inline const std::string& RPCPacket::created_time() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.created_time)
  return _internal_created_time();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPCPacket::set_created_time(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.created_time_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.created_time)
}
inline std::string* RPCPacket::mutable_created_time() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_created_time();
  // @@protoc_insertion_point(field_mutable:DSFramework.DSRPC.Packet.RPCPacket.created_time)
  return _s;
}
inline const std::string& RPCPacket::_internal_created_time() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.created_time_.Get();
}
inline void RPCPacket::_internal_set_created_time(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.created_time_.Set(value, GetArena());
}
inline std::string* RPCPacket::_internal_mutable_created_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.created_time_.Mutable( GetArena());
}
inline std::string* RPCPacket::release_created_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DSFramework.DSRPC.Packet.RPCPacket.created_time)
  return _impl_.created_time_.Release();
}
inline void RPCPacket::set_allocated_created_time(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.created_time_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.created_time_.IsDefault()) {
          _impl_.created_time_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.created_time)
}

// string commited_time = 8;
inline void RPCPacket::clear_commited_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.commited_time_.ClearToEmpty();
}
inline const std::string& RPCPacket::commited_time() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.commited_time)
  return _internal_commited_time();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPCPacket::set_commited_time(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.commited_time_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.commited_time)
}
inline std::string* RPCPacket::mutable_commited_time() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_commited_time();
  // @@protoc_insertion_point(field_mutable:DSFramework.DSRPC.Packet.RPCPacket.commited_time)
  return _s;
}
inline const std::string& RPCPacket::_internal_commited_time() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.commited_time_.Get();
}
inline void RPCPacket::_internal_set_commited_time(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.commited_time_.Set(value, GetArena());
}
inline std::string* RPCPacket::_internal_mutable_commited_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.commited_time_.Mutable( GetArena());
}
inline std::string* RPCPacket::release_commited_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DSFramework.DSRPC.Packet.RPCPacket.commited_time)
  return _impl_.commited_time_.Release();
}
inline void RPCPacket::set_allocated_commited_time(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.commited_time_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.commited_time_.IsDefault()) {
          _impl_.commited_time_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.commited_time)
}

// string completed_time = 9;
inline void RPCPacket::clear_completed_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.completed_time_.ClearToEmpty();
}
inline const std::string& RPCPacket::completed_time() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.completed_time)
  return _internal_completed_time();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPCPacket::set_completed_time(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.completed_time_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.completed_time)
}
inline std::string* RPCPacket::mutable_completed_time() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_completed_time();
  // @@protoc_insertion_point(field_mutable:DSFramework.DSRPC.Packet.RPCPacket.completed_time)
  return _s;
}
inline const std::string& RPCPacket::_internal_completed_time() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.completed_time_.Get();
}
inline void RPCPacket::_internal_set_completed_time(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.completed_time_.Set(value, GetArena());
}
inline std::string* RPCPacket::_internal_mutable_completed_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.completed_time_.Mutable( GetArena());
}
inline std::string* RPCPacket::release_completed_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DSFramework.DSRPC.Packet.RPCPacket.completed_time)
  return _impl_.completed_time_.Release();
}
inline void RPCPacket::set_allocated_completed_time(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.completed_time_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.completed_time_.IsDefault()) {
          _impl_.completed_time_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.completed_time)
}

// string request_id = 10;
inline void RPCPacket::clear_request_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.request_id_.ClearToEmpty();
}
inline const std::string& RPCPacket::request_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.request_id)
  return _internal_request_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPCPacket::set_request_id(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.request_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.request_id)
}
inline std::string* RPCPacket::mutable_request_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_request_id();
  // @@protoc_insertion_point(field_mutable:DSFramework.DSRPC.Packet.RPCPacket.request_id)
  return _s;
}
inline const std::string& RPCPacket::_internal_request_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.request_id_.Get();
}
inline void RPCPacket::_internal_set_request_id(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.request_id_.Set(value, GetArena());
}
inline std::string* RPCPacket::_internal_mutable_request_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.request_id_.Mutable( GetArena());
}
inline std::string* RPCPacket::release_request_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DSFramework.DSRPC.Packet.RPCPacket.request_id)
  return _impl_.request_id_.Release();
}
inline void RPCPacket::set_allocated_request_id(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.request_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.request_id_.IsDefault()) {
          _impl_.request_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.request_id)
}

// string service = 11;
inline void RPCPacket::clear_service() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.service_.ClearToEmpty();
}
inline const std::string& RPCPacket::service() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.service)
  return _internal_service();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPCPacket::set_service(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.service_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DSFramework.DSRPC.Packet.RPCPacket.service)
}
inline std::string* RPCPacket::mutable_service() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_service();
  // @@protoc_insertion_point(field_mutable:DSFramework.DSRPC.Packet.RPCPacket.service)
  return _s;
}
inline const std::string& RPCPacket::_internal_service() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.service_.Get();
}
inline void RPCPacket::_internal_set_service(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.service_.Set(value, GetArena());
}
inline std::string* RPCPacket::_internal_mutable_service() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.service_.Mutable( GetArena());
}
inline std::string* RPCPacket::release_service() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DSFramework.DSRPC.Packet.RPCPacket.service)
  return _impl_.service_.Release();
}
inline void RPCPacket::set_allocated_service(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.service_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.service_.IsDefault()) {
          _impl_.service_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.service)
}

// .google.protobuf.Any parameters = 12;
inline bool RPCPacket::has_parameters() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.parameters_ != nullptr);
  return value;
}
inline const ::google::protobuf::Any& RPCPacket::_internal_parameters() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::google::protobuf::Any* p = _impl_.parameters_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Any&>(::google::protobuf::_Any_default_instance_);
}
inline const ::google::protobuf::Any& RPCPacket::parameters() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.parameters)
  return _internal_parameters();
}
inline void RPCPacket::unsafe_arena_set_allocated_parameters(::google::protobuf::Any* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.parameters_);
  }
  _impl_.parameters_ = reinterpret_cast<::google::protobuf::Any*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.parameters)
}
inline ::google::protobuf::Any* RPCPacket::release_parameters() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Any* released = _impl_.parameters_;
  _impl_.parameters_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::Any* RPCPacket::unsafe_arena_release_parameters() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DSFramework.DSRPC.Packet.RPCPacket.parameters)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Any* temp = _impl_.parameters_;
  _impl_.parameters_ = nullptr;
  return temp;
}
inline ::google::protobuf::Any* RPCPacket::_internal_mutable_parameters() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.parameters_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::Any>(GetArena());
    _impl_.parameters_ = reinterpret_cast<::google::protobuf::Any*>(p);
  }
  return _impl_.parameters_;
}
inline ::google::protobuf::Any* RPCPacket::mutable_parameters() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::Any* _msg = _internal_mutable_parameters();
  // @@protoc_insertion_point(field_mutable:DSFramework.DSRPC.Packet.RPCPacket.parameters)
  return _msg;
}
inline void RPCPacket::set_allocated_parameters(::google::protobuf::Any* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.parameters_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.parameters_ = reinterpret_cast<::google::protobuf::Any*>(value);
  // @@protoc_insertion_point(field_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.parameters)
}

// .google.protobuf.Any result = 13;
inline bool RPCPacket::has_result() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.result_ != nullptr);
  return value;
}
inline const ::google::protobuf::Any& RPCPacket::_internal_result() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::google::protobuf::Any* p = _impl_.result_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Any&>(::google::protobuf::_Any_default_instance_);
}
inline const ::google::protobuf::Any& RPCPacket::result() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DSFramework.DSRPC.Packet.RPCPacket.result)
  return _internal_result();
}
inline void RPCPacket::unsafe_arena_set_allocated_result(::google::protobuf::Any* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.result_);
  }
  _impl_.result_ = reinterpret_cast<::google::protobuf::Any*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.result)
}
inline ::google::protobuf::Any* RPCPacket::release_result() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::Any* released = _impl_.result_;
  _impl_.result_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::Any* RPCPacket::unsafe_arena_release_result() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DSFramework.DSRPC.Packet.RPCPacket.result)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::Any* temp = _impl_.result_;
  _impl_.result_ = nullptr;
  return temp;
}
inline ::google::protobuf::Any* RPCPacket::_internal_mutable_result() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.result_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::Any>(GetArena());
    _impl_.result_ = reinterpret_cast<::google::protobuf::Any*>(p);
  }
  return _impl_.result_;
}
inline ::google::protobuf::Any* RPCPacket::mutable_result() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::Any* _msg = _internal_mutable_result();
  // @@protoc_insertion_point(field_mutable:DSFramework.DSRPC.Packet.RPCPacket.result)
  return _msg;
}
inline void RPCPacket::set_allocated_result(::google::protobuf::Any* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.result_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.result_ = reinterpret_cast<::google::protobuf::Any*>(value);
  // @@protoc_insertion_point(field_set_allocated:DSFramework.DSRPC.Packet.RPCPacket.result)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Packet
}  // namespace DSRPC
}  // namespace DSFramework


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::DSFramework::DSRPC::Packet::RPCPacketError> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::DSFramework::DSRPC::Packet::RPCPacketError>() {
  return ::DSFramework::DSRPC::Packet::RPCPacketError_descriptor();
}
template <>
struct is_proto_enum<::DSFramework::DSRPC::Packet::RPCPacketType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::DSFramework::DSRPC::Packet::RPCPacketType>() {
  return ::DSFramework::DSRPC::Packet::RPCPacketType_descriptor();
}
template <>
struct is_proto_enum<::DSFramework::DSRPC::Packet::RPCPacketStatus> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::DSFramework::DSRPC::Packet::RPCPacketStatus>() {
  return ::DSFramework::DSRPC::Packet::RPCPacketStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_RPCPacket_2eproto_2epb_2eh
